modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/SilentChaos512/FunOres/issues"
displayURL="https://minecraft.curseforge.com/projects/fun-ores"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="SilentChaos512"

[[mods]]
    modId="funores"
    version="${file.jarVersion}"
    displayName="Fun Ores"
    description='''
    Adds ores which drop items from certain mobs.

    Former versions also added metals. This is no longer a feature of the mod.
    '''

[[dependencies.funores]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.funores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.funores]]
    modId="silentlib"
    mandatory=true
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"