modLoader="javafml"
loaderVersion="[27,)"
#updateJSONURL="http://myurl.me/" #optional
issueTrackerURL="https://github.com/SilentChaos512/FunOres/issues"
displayURL="https://minecraft.curseforge.com/projects/fun-ores"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="SilentChaos512"

[[mods]]
modId="funores"
version="${file.jarVersion}"
displayName="Fun Ores"
description='''
Adds ores which drop items from certain mobs.

Former versions also added metals. This is no longer a feature of the mod.
'''

[[dependencies.funores]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.funores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.funores]]
    modId="silentlib"
    mandatory=true
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"