@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.funores.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;