@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.funores.config;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;