@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.funores.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;