@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.funores.init;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;