@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.funores.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;